### ISSUE TITLE
{noformat} doesn't

### ISSUE THREAD

**Issue by rspilker** [FokkeZB/J2M#11]
From the [example page](http://j2m.fokkezb.nl/):

```
{noformat}
  preformatted piece of text
  so *no* further _formatting_ is done here
{noformat}
```

converts to

    ```
      preformatted piece of text
      so **no** further *formatting* is done here
    ```

So `*no*` is changed to `**no**` and `_formatting_` to `*formatting*`.

I expected everything between the `{noformat}` to remain the same.

**Comment by FokkeZB** [comment]
Mmm, yes.. that makes sense given the very simple [replacements](https://github.com/FokkeZB/J2M/blob/master/src/J2M.js) it does.

Unfortunately I cannot spent time on this atm, but I'm open for PRs!

**Comment by rspilker** [comment]
I understand. 

Regular expressions are not usable at all. I've tried to parse the JIRA format myself, but there is no specification, just some very simple examples. There are some implicit rules regarding nesting, no difference between opening and ending "tags". No grammar available at all and a lot of corner cases, as far as I could see.

I think the best approach is to have JIRA render the HTML (also possible via the API), and then convert the HTML to Markdown. In general, that is very hard, but in this case good to do since JIRA only uses a small subset of HTML.

**Comment by FokkeZB** [comment]
JIRA's format is actually Textile plus some extras, so it might be a good idea for J2M to use Pandoc and plus some additional conversions.

http://pandoc.org/
http://pandoc.org/try/

**Comment by FokkeZB** [comment]
Closing for #12
