### ISSUE TITLE
Markdown -> Jira goes nuts when code section contains `command substitution`

### ISSUE THREAD

**Issue by rusq** [FokkeZB/J2M#15]
Please see example Markdown code:
<pre>
2. Wizard:
```
echo `pwd` 20
```
</pre>

**Comment by FokkeZB** [comment]
Could you share an example of the unexpected result?

**Comment by rusq** [comment]
Hi, and thank you for attending this.

Sure, as an example, I copied the verbatim part from above commentary and pasted it on the [J2M site](http://j2m.fokkezb.nl/) to the **Markdown** half of the converter. Result is the following:
Source Markdown
<pre>
2. Wizard:
```
echo `pwd` 20
```
</pre>
Gets converted to:
<pre>
2. Wizard:
``{{
echo }}pwd{{ 20
}}``
</pre>

Notice the <pre>``{{</pre> sequence which breaks jira formatting of the rest of the post.

**Comment by FokkeZB** [comment]
Could you test if https://github.com/FokkeZB/J2M/commit/34c3452239b1f156cfd285330f1e8b4089980d95 fixes it?

**Comment by rusq** [comment]
Thanks for a quick fix, @FokkeZB !

I checked it, JIRA is happy now (formatting is not spoiled), but this still changes the meaning of the message. I'll rephrase the example to use more generic commands.

I want to write the following:
> Run the following command:
> ```
> echo The following: `date` is the current date 
> ```

So I create the following markdown for it:
<pre>
Run the following command:
```
echo The following: `date` is the current date 
```
</pre>

I convert it with the J2M converter, receiving the following source text:
<pre>
Run the following command:
{code}
echo The following: {{date}} is the current date 
{code}
</pre>

When I paste it to JIRA it produces the following output:
> Run the following command:
> ```
> echo The following: {{date}} is the current date
> ```

The meaning of the message has changed, and the code will not work.

It's much easier to correct now, but still would be really nice if library would take care of this, relieving a person from the manual labour.

**Comment by FokkeZB** [comment]
Mmm, of course... anything inside `{code} .. {code}` shouldn't be formatted. That'll be a bit hard to do with plain regex though. I think this falls in the category that #12 should fix, but unfortunately I don't have time to do so.

**Comment by rusq** [comment]
No worries, thanks.
