### ISSUE TITLE
Nested formatting

### ISSUE THREAD

**Issue by paoloantinori** [FokkeZB/J2M#18]
Hi, I'm using your lib in a Firefox extension, so I've been actively testing this.

I have encountered a set of issues with rendering. I'm planning to fix them myself as much as I can, but in the meanwhile I will start to just report them here to start keeping track of them.

** Nested Formatting Broken Behavior **

The expectation is that this snippet:

![screenshot from 2016-09-21 16-37-05](https://cloud.githubusercontent.com/assets/1520602/18715481/c0819542-8019-11e6-9192-3bc377f35b16.png)

won't interpret the content of a block of text as JIRA formatting, instead this is what it produces:

![screenshot from 2016-09-21 16-37-12](https://cloud.githubusercontent.com/assets/1520602/18715505/dcdf346a-8019-11e6-9b09-58281a29ce55.png)

**Comment by FokkeZB** [comment]
Good one, probably best to try to do #12 if you have time :S

**Comment by paoloantinori** [comment]
Thanks, I will try to give it a look!
