### ISSUE TITLE
tables are not converted.

### ISSUE THREAD

**Issue by karelv** [FokkeZB/J2M#20]
jira tables are not converted:
https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=tables
```
||heading 1||heading 2||heading 3||
|col A1|col A2|col A3|
|col B1|col B2|col B3|
```

nor are markdown tables converted:
http://www.tablesgenerator.com/markdown_tables
```
| d | e |
|---|---|
|   |   |
```

**Comment by FokkeZB** [comment]
Indeed, it just uses a [simple set of regexps](https://github.com/FokkeZB/J2M/blob/master/src/J2M.js). This would be best closed via #12, but I don't have time for that atm unfortunately. I'm open for PRs though!
