### ISSUE TITLE
Conversion from stdin looses linebreaks

### ISSUE THREAD

**Issue by Jafu** [FokkeZB/J2M#21]
You can reproduce it using the following cmd:
```
echo "1\n2" | j2m -j --stdin
```
This produces the following result:
```
12
```
But it should result be:
```
1
2
```

**Comment by pjf** [comment]
Came here to report this as well, to discover it's already fixed. Thank you! I don't suppose we'll see another npm release soon?

Many thanks again for a great tool!

~ Paul

**Comment by FokkeZB** [comment]
With pleasure!  https://www.npmjs.com/package/j2m

**Comment by pjf** [comment]
@FokkeZB : You *rock*, thank you! <3
