### ISSUE TITLE
Nested Formatting #2

### ISSUE THREAD

**Issue by paoloantinori** [FokkeZB/J2M#26]
Hi, I think I have found a new issue with nested formatting but I'd like to check with you first, since maybe I just have the wrong expectations.

Try to convert from MD to JIRA this expression:

```
`<test>`
```

What should we expect? to find the angle brackets in the output or is it correct to have them corrected to squared ones?

J2M currently converts it to:

```
{{[test]}}
```

**Comment by FokkeZB** [comment]
@paoloantinori I think it should be {{<test>}} as the idea is to keep the contents unformatted.

Would you have time to do a PR?

**Comment by paoloantinori** [comment]
Sure I'll take care of that
