### ISSUE TITLE
Markdown Images failed to be converted to JIRA format

### ISSUE THREAD

**Issue by AlphaGit** [FokkeZB/J2M#29]
Inputting the following:

    ![yUML Generated image](http://yuml.me/3719ae27)

Will generate the following JIRA formatting:

    ![yUML Generated image|http://yuml.me/3719ae27]

Which is a link prepended by an exclamation mark (`!`), but it should actually be an image:

    !http://yuml.me/3719ae27!

**Comment by FokkeZB** [comment]
Thanks for spotting that @AlphaGit! Would you be able to do a PR?

**Comment by AlphaGit** [comment]
Sure! It might take me a couple of days, but I'll get to it. If I don't provide something for this next weekend, I'll report back and leave it open for someone else.
