### ISSUE TITLE
Provide library

### ISSUE THREAD

**Issue by j6s** [FokkeZB/J2M#8]
Hello,

I stumbled upon this tool and I love it. However I think it would be nice to use the logic encapsuled.
I have forked the repository and will refactor the code to fit this requirement.

While I am doing that I will also make it ready to use as a Node module.
Context: I want to write a command line utility that does the conversion, so you can do something like this:

```
j2m --toJ notes.md | pbcopy
```

I will provide my changes as a pull request and hope that they are not to radical. 
I want to give you the chance to publish it to npm yourself if you want to. (If not, I will fork the repository for good and publish the fork)

Expect the PR this week.

**Comment by FokkeZB** [comment]
Hi,

Thanks in advance! This was just a wip, so contribs are more than welcome!

**Comment by FokkeZB** [comment]
👏
